[package]
name = "atlas-sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atlas-core = { path = "../atlas-core" }
libmount = "0.1.15"
fuser = "0.11.0"
libc = "0.2"
uuid = { version = "0.8", features = ["v4"] }
bimap = "0.6.2"
async-channel = "1.6"